name: Run MRS Conversion
on:
  push:
    paths:
      - scripts/convert-rule-providers-to-mrs.py
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python scripts/convert-rule-providers-to-mrs.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: chore: convert rule providers to mrs
          file_pattern: 防DNS泄露.yaml 防DNS泄露.js
